export const players = [
  {
    id: "andrey",
    name: "Andrey",
    location: "Franklin",
    lat: 35.9271,
    lng: -86.8689,
    color: "#FF5A5F",
  },
  {
    id: "lucas",
    name: "Lucas",
    location: "Murfreesboro",
    lat: 35.8456,
    lng: -86.3897,
    color: "#00A699",
  },
];

export const courts = [
  {
    id: "316-tennis",
    name: "316 Tennis",
    address: "4629 Murfreesboro Rd, Franklin, TN",
    lat: 35.9088,
    lng: -86.7987,
    price: "$40/hr",
    priceNote: "Court Reserve",
    bookingPlatform: "Court Reserve",
    bookingUrl: "https://app.courtreserve.com/",
    bookingIos: "https://apps.apple.com/app/court-reserve/id1447850498",
    bookingAndroid: "https://play.google.com/store/apps/details?id=com.courtreserve.app",
    website: "https://www.threesixteentennis.com/",
    phone: "(615) 604-3218",
    hours: "Call for availability",
    bookingRules: "Court Reserve account required",
    pricingDetails: "Indoor court time from $40/hr",
    amenities: ["Indoor courts", "Outdoor courts", "Pro shop"],
    indoor: true,
    outdoor: true,
    type: "Indoor + Outdoor",
    marker: { color: "#4A90D9", label: "316", icon: "text" },
    theme: "linear-gradient(135deg, #4A90D9, #8FC3F7)",
    drive: { andrey: 8, lucas: 30 },
  },
  {
    id: "farm-forge",
    name: "Farm & Forge",
    address: "8445 Horton Hwy, College Grove, TN",
    lat: 35.7445,
    lng: -86.7034,
    price: "Members",
    priceNote: "Club Automation",
    bookingPlatform: "Club Automation",
    bookingUrl: "https://farmandforge.clubautomation.com/",
    website: "https://farmandforgeclub.com/",
    phone: "",
    hours: "Call for availability",
    bookingRules: "Member booking only",
    pricingDetails: "Members-only facility",
    amenities: ["Outdoor courts", "Clubhouse"],
    indoor: false,
    outdoor: true,
    type: "Outdoor",
    marker: { color: "#2E7D32", label: "", icon: "leaf" },
    theme: "linear-gradient(135deg, #2E7D32, #66BB6A)",
    drive: { andrey: 25, lucas: 35 },
  },
  {
    id: "adams",
    name: "Adams Tennis",
    address: "925 Golf Lane, Murfreesboro, TN",
    lat: 35.8497,
    lng: -86.3899,
    price: "$15-20",
    priceNote: "City booking",
    bookingPlatform: "City of Murfreesboro",
    bookingUrl: "https://www.murfreesborotn.gov/807/Adams-Tennis-Complex",
    website: "https://www.murfreesborotn.gov/807/Adams-Tennis-Complex",
    phone: "(615) 546-4000",
    hours: "Call for availability",
    bookingRules: "Reserve online or by phone",
    pricingDetails: "$15-20/hr depending on court",
    amenities: ["Indoor courts", "Pro shop"],
    indoor: true,
    outdoor: false,
    type: "Indoor",
    marker: { color: "#FF7043", label: "A", icon: "text" },
    theme: "linear-gradient(135deg, #FF7043, #FFAB91)",
    drive: { andrey: 35, lucas: 8 },
  },
  {
    id: "maryland-farms",
    name: "Tennis Complex at Maryland Farms",
    address: "5101 Maryland Way, Brentwood, TN 37027",
    lat: 36.0318,
    lng: -86.7828,
    price: "$26/hr indoor · $12/hr outdoor",
    priceNote: "Williamson County Parks",
    bookingPlatform: "Williamson County Parks",
    bookingUrl: "https://anc.apm.activecommunities.com/wcpr/reservation/landing",
    website: "https://www.wcparksandrec.com/facilities_and_parks/tennis_complex_at_maryland_farms/",
    phone: "(615) 376-9257",
    hours: "Mon-Thu 8am-8pm, Fri 8am-6pm, Sat-Sun 8am-5pm",
    bookingRules: "Reservations 3 days in advance at 8am. Online only. Max 2 hours/day.",
    pricingDetails: "Indoor $26/hr · Outdoor $12/hr",
    amenities: ["Indoor courts", "Outdoor courts", "Racquetball", "Pickleball"],
    indoor: true,
    outdoor: true,
    type: "Indoor + Outdoor",
    marker: { color: "#9C27B0", label: "MF", icon: "text" },
    theme: "linear-gradient(135deg, #9C27B0, #CE93D8)",
    drive: { andrey: 12, lucas: 40 },
  },
  {
    id: "centennial",
    name: "Centennial Sportsplex Tennis",
    address: "224 25th Ave N, Nashville, TN 37203",
    lat: 36.152,
    lng: -86.8086,
    price: "~$5/hr outdoor",
    priceNote: "Nashville Parks",
    bookingPlatform: "Call or online",
    bookingUrl: "https://www.nashville.gov/departments/parks/centennial-sportsplex/tennis",
    website: "https://www.nashville.gov/departments/parks/centennial-sportsplex/tennis",
    phone: "(615) 862-8490",
    hours: "Varies, call for availability",
    bookingRules: "Reserve by phone or online",
    pricingDetails: "~$5/hr outdoor · indoor contract time available",
    amenities: ["Indoor courts", "Outdoor courts", "Pro shop"],
    indoor: true,
    outdoor: true,
    type: "Indoor (4) + Outdoor (9)",
    note: "Nashville's premier public tennis facility",
    marker: { color: "#E53935", label: "", icon: "star" },
    theme: "linear-gradient(135deg, #E53935, #FF8A80)",
    drive: { andrey: 30, lucas: 50 },
  },
  {
    id: "wc-indoor",
    name: "Williamson County Indoor Sports Complex",
    address: "920 Heritage Way, Brentwood, TN 37027",
    lat: 35.989,
    lng: -86.753,
    price: "$26/hr indoor · $12/hr outdoor",
    priceNote: "Williamson County Parks",
    bookingPlatform: "Williamson County Parks",
    bookingUrl: "https://anc.apm.activecommunities.com/wcpr/reservation/landing",
    website: "https://www.wcparksandrec.com/athletics/adult_sports/tennis/",
    phone: "(615) 370-3471",
    hours: "Call for availability",
    bookingRules: "Reservations 3 days in advance, online only",
    pricingDetails: "Indoor $26/hr · Outdoor $12/hr",
    amenities: ["Indoor courts", "Fitness facilities"],
    indoor: true,
    outdoor: false,
    type: "Indoor",
    marker: { color: "#00897B", label: "", icon: "building" },
    theme: "linear-gradient(135deg, #00897B, #80CBC4)",
    drive: { andrey: 15, lucas: 38 },
  },
];
