export const players = [
  {
    id: "andrey",
    name: "Andrey",
    location: "Franklin",
    lat: 35.9271,
    lng: -86.8689,
    color: "#FF5A5F",
  },
  {
    id: "lucas",
    name: "Lucas",
    location: "Murfreesboro",
    lat: 35.8456,
    lng: -86.3897,
    color: "#00A699",
  },
];

export const courts = [
  {
    id: "316-tennis",
    name: "316 Tennis",
    address: "4629 Murfreesboro Rd, Franklin, TN",
    lat: 35.9088,
    lng: -86.7987,
    price: "$40/hr",
    priceNote: "Court Reserve",
    bookingPlatform: "Court Reserve",
    bookingUrl: "https://app.courtreserve.com/",
    bookingIos: "https://apps.apple.com/app/court-reserve/id1447850498",
    bookingAndroid: "https://play.google.com/store/apps/details?id=com.courtreserve.app",
    website: "https://www.threesixteentennis.com/",
    phone: "(615) 604-3218",
    indoor: true,
    outdoor: true,
    theme: "linear-gradient(135deg, #FF5A5F, #FF9A8B)",
    drive: { andrey: 8, lucas: 30 },
  },
  {
    id: "farm-forge",
    name: "Farm & Forge",
    address: "8445 Horton Hwy, College Grove, TN",
    lat: 35.7445,
    lng: -86.7034,
    price: "Members",
    priceNote: "Club Automation",
    bookingPlatform: "Club Automation",
    bookingUrl: "https://farmandforge.clubautomation.com/",
    website: "https://farmandforgeclub.com/",
    phone: "",
    indoor: false,
    outdoor: true,
    theme: "linear-gradient(135deg, #00A699, #7BE0C3)",
    drive: { andrey: 25, lucas: 35 },
  },
  {
    id: "adams",
    name: "Adams Tennis",
    address: "925 Golf Lane, Murfreesboro, TN",
    lat: 35.8497,
    lng: -86.3899,
    price: "$15-20",
    priceNote: "City booking",
    bookingPlatform: "City of Murfreesboro",
    bookingUrl: "https://www.murfreesborotn.gov/807/Adams-Tennis-Complex",
    website: "https://www.murfreesborotn.gov/807/Adams-Tennis-Complex",
    phone: "(615) 546-4000",
    indoor: true,
    outdoor: false,
    theme: "linear-gradient(135deg, #222222, #6E6E6E)",
    drive: { andrey: 35, lucas: 8 },
  },
];
