export const courts = [
  {
    id: "jim-warren",
    name: "Jim Warren Park",
    address: "1008 Critz Ln, Franklin, TN",
    type: "Outdoor",
    surface: "Hard",
    courts: 4,
    busyTimes: "Weekday evenings, Saturday mornings",
    rating: 4.4,
    amenities: ["Lights", "Restrooms", "Water"],
    bookingUrl: "https://www.google.com/maps/search/?api=1&query=Jim+Warren+Park+Franklin+TN",
    locationCategory: "franklin"
  },
  {
    id: "fieldstone",
    name: "Fieldstone Park",
    address: "409 Fieldstone Pkwy, Franklin, TN",
    type: "Outdoor",
    surface: "Hard",
    courts: 2,
    busyTimes: "Weekday afternoons",
    rating: 4.0,
    amenities: ["Restrooms", "Water"],
    bookingUrl: "https://www.google.com/maps/search/?api=1&query=Fieldstone+Park+Franklin+TN",
    locationCategory: "franklin"
  },
  {
    id: "harlinsdale",
    name: "Harlinsdale Farm",
    address: "239 Franklin Rd, Franklin, TN",
    type: "Outdoor",
    surface: "Hard",
    courts: 2,
    busyTimes: "Sunday afternoons",
    rating: 4.2,
    amenities: ["Lights", "Restrooms"],
    bookingUrl: "https://www.google.com/maps/search/?api=1&query=Harlinsdale+Farm+Franklin+TN",
    locationCategory: "franklin"
  },
  {
    id: "franklin-athletic",
    name: "Franklin Athletic Club",
    address: "501 Lewisburg Ave, Franklin, TN",
    type: "Indoor",
    surface: "Hard",
    courts: 6,
    busyTimes: "Weekday mornings",
    rating: 4.8,
    amenities: ["Lights", "Restrooms", "Water"],
    bookingUrl: "https://www.google.com/maps/search/?api=1&query=Franklin+Athletic+Club",
    locationCategory: "franklin"
  },
  {
    id: "old-fort",
    name: "Old Fort Park",
    address: "916 Golf Ln, Murfreesboro, TN",
    type: "Outdoor",
    surface: "Hard",
    courts: 8,
    busyTimes: "Weekday evenings, Sunday mornings",
    rating: 4.6,
    amenities: ["Lights", "Restrooms", "Water"],
    bookingUrl: "https://www.google.com/maps/search/?api=1&query=Old+Fort+Park+Murfreesboro+TN",
    locationCategory: "murfreesboro"
  },
  {
    id: "sportscom",
    name: "SportsCom",
    address: "2310 Memorial Blvd, Murfreesboro, TN",
    type: "Indoor",
    surface: "Hard",
    courts: 6,
    busyTimes: "Weekday evenings",
    rating: 4.5,
    amenities: ["Restrooms", "Water"],
    bookingUrl: "https://www.google.com/maps/search/?api=1&query=SportsCom+Murfreesboro+TN",
    locationCategory: "murfreesboro"
  },
  {
    id: "adams",
    name: "Adams Tennis Complex",
    address: "MTSU Campus, Murfreesboro, TN",
    type: "Outdoor",
    surface: "Clay",
    courts: 12,
    busyTimes: "Weekday late afternoons",
    rating: 4.9,
    amenities: ["Lights", "Restrooms", "Water"],
    bookingUrl: "https://www.google.com/maps/search/?api=1&query=Adams+Tennis+Complex+Murfreesboro+TN",
    locationCategory: "murfreesboro"
  },
  {
    id: "barfield",
    name: "Barfield Crescent Park",
    address: "697 Veterans Pkwy, Murfreesboro, TN",
    type: "Outdoor",
    surface: "Hard",
    courts: 4,
    busyTimes: "Saturday mornings",
    rating: 4.1,
    amenities: ["Lights", "Restrooms"],
    bookingUrl: "https://www.google.com/maps/search/?api=1&query=Barfield+Crescent+Park+Murfreesboro+TN",
    locationCategory: "murfreesboro"
  },
  {
    id: "lee-victory",
    name: "Lee Victory Recreation Park",
    address: "Smyrna, TN",
    type: "Outdoor",
    surface: "Hard",
    courts: 4,
    busyTimes: "Weekday evenings",
    rating: 4.0,
    amenities: ["Lights", "Restrooms", "Water"],
    bookingUrl: "https://www.google.com/maps/search/?api=1&query=Lee+Victory+Recreation+Park+Smyrna+TN",
    locationCategory: "smyrna"
  },
  {
    id: "cedar-stone",
    name: "Cedar Stone Park",
    address: "La Vergne, TN",
    type: "Outdoor",
    surface: "Hard",
    courts: 3,
    busyTimes: "Sunday afternoons",
    rating: 3.8,
    amenities: ["Restrooms"],
    bookingUrl: "https://www.google.com/maps/search/?api=1&query=Cedar+Stone+Park+La+Vergne+TN",
    locationCategory: "smyrna"
  }
];
